# This is a basic workflow to help you get started with Actions
name: Checkmarx_Scans

# Controls when the action will run. 
on:
  # Triggers the workflow on push master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Scan code with Checkmarx
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
        with:
          project: PHPProject
          team: /CxServer
          checkmarx_url: http://340a14adf519.ngrok.io
          checkmarx_username: admin@cx
          checkmarx_password: Password123@456
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          break_build: false
          scanners: sast
