# This is a basic workflow to help you get started with Actions
name: Checkmarx_Scans

# Controls when the action will run. 
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: self-hosted 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Scan code with Checkmarx
      - name: Checkmarx CxFlow Action
        #run: echo Hello, world! 
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
        with:
          project: PHPProject
          team: CxServer
          checkmarx_url: http://52.31.179.105/
          checkmarx_username: admin@cx
          checkmarx_password: H#c2iN36M!
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          break_build: false
          scanners: sast
          
            # Upload SARIF report for CodeQL / Security Alerts PRocessing
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: cx.sarif
